baseURL = "https://frenchu.github.io/pragmatic-programming"
languageCode = "en-us"
title = "Pragmatic Programming"
theme = "beautifulhugo"

enableGitInfo = true
pygmentsCodeFences = true
pygmentsUseClasses = true
disqusShortname = "frenchu85"
