theme = "hugo-coder"
baseURL = "https://pawelweselak.com/"
title = "Pragmatic Programming"
paginate = 20
canonifyUrls = true

languageCode = "en"
defaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
pygmentsCodeFences = true
pygmentsUseClasses = true
disqusShortName = "pragmatic-programming"

[outputs]
    home = ["HTML", "RSS", "JSON"]

[params]
    author = "Paweł Weselak"
    description = "Paweł Weselak pragmatyczne programowanie"
    keywords = "blog,developer,personal"
    info = "Senior Software Developer"
    gravatar = "frenchu@o2.pl"
    footercontent = "Everything should be as simple as possible, but not simplier."
    commit = "https://github.com/frenchu/pragmatic-programming/tree/"
    dateformat = "January 2, 2006"

    hideFooter = false
    hideCredits = false
    hideCopyright = false
    since = 2018

    rtl = false

    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    colorscheme = "auto"

    # Series see also post count
    maxSeeAlsoItems = 5

[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"


[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/frenchu/"

[[params.social]]
    name = "Gitlab"
    icon = "fab fa-gitlab"
    weight = 2
    url = "https://gitlab.com/frenchu/"

[[params.social]]
    name = "Stackoverflow"
    icon = "fab fa-stack-overflow"
    weight = 3
    url = "https://stackoverflow.com/users/4871030/pawe%c5%82-weselak"

[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 4
    url = "https://www.linkedin.com/in/pawel-weselak/"


[[Menus.main]]
    name = "About"
    weight = 1
    url = "about/"

[[Menus.main]]
    name = "Projects"
    weight = 2
    url = "projects/"

[[Menus.main]]
    name = "Posts"
    weight = 3
    url = "posts/"

[[Menus.main]]
    name = "Categories"
    weight = 4
    url = "categories/"

[[Menus.main]]
    name = "Tags"
    weight = 5
    url = "tags/"

[[Menus.main]]
    name = "Search"
    weight = 6
    url = "search/"
