theme = ["hugo-coder"]
baseURL = "https://pawelweselak.com/"
title = "Pragmatic Programming"
paginate = 20
canonifyUrls = true

languageCode = "en"
defaultContentLanguage = "en"
enableInlineShortcodes = true
enableGitInfo = true
enableEmoji = true
footnoteReturnLinkContents = "^"
pygmentsCodeFences = true
pygmentsUseClasses = true
pygmentsCodeFencesGuessSyntax = true
disqusShortName = "pragmatic-programming"

[outputs]
    home = ["HTML", "RSS", "JSON"]

[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"

[params]
    author = "Paweł Weselak"
    description = "Blog of Paweł Weselak pragmatyczne programowanie"
    keywords = "Paweł Weselak,personal blog,senior java developer,senior software engineer"
    info = "Senior Software Developer"
    footerContent = "Everything should be as simple as possible, but not simplier."
    commit = "https://github.com/frenchu/pragmatic-programming/tree"
    dateformat = "January 2, 2006"
    avatarUrl = "images/avatar.jpg"
    # gravatar = "blog@pawelweselak.com"

    hideFooter = false
    hideCredits = false
    hideCopyright = false
    since = 2010

    rtl = false

    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    colorScheme = "auto"
    hideColorSchemeToggle = false

    # Series see also post count
    maxSeeAlsoItems = 5

# Social links
[[params.social]]
    name = "Github"
    icon = "fa fa-github fa-2x"
    weight = 1
    url = "https://github.com/frenchu"

[[params.social]]
    name = "Stackoverflow"
    icon = "fa fa-stack-overflow fa-2x"
    weight = 2
    url = "https://stackoverflow.com/users/4871030/frenchu"

[[params.social]]
    name = "LinkedIn"
    icon = "fa fa-linkedin fa-2x"
    weight = 3
    url = "https://www.linkedin.com/in/pawel-weselak/"

[[params.social]]
    name = "Twitter"
    icon = "fa fa-twitter fa-2x"
    weight = 4
    url = "https://twitter.com/frenchu85"

# Menu links
[[menu.main]]
    name = "About"
    weight = 1
    url = "about/"

[[menu.main]]
    name = "Projects"
    weight = 2
    url = "projects/"

[[menu.main]]
    name = "Posts"
    weight = 3
    url = "posts/"

[[menu.main]]
    name = "Categories"
    weight = 4
    url = "categories/"

[[menu.main]]
    name = "Tags"
    weight = 5
    url = "tags/"

# Privacy settings
[privacy]

  [privacy.disqus]
    disable = true

  [privacy.googleAnalytics]
    disable = true

  [privacy.instagram]
    disable = true

  [privacy.twitter]
    disable = true

  [privacy.vimeo]
    disable = true

  [privacy.youtube]
    disable = true
