baseURL = "https://pawelweselak.com/"
canonifyUrls = true
defaultContentLanguage = "en"
disqusShortName = "pragmatic-programming"
enableEmoji = true
enableGitInfo = true
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
languageCode = "en"
paginate = 20
pygmentsCodeFences = true
pygmentsUseClasses = true
theme = "hugo-coder"
title = "Pragmatic Programming"
[[menu.main]]
name = "Search"
url = "search/"
weight = 6
[[menu.main]]
name = "Tags"
url = "tags/"
weight = 5
[[menu.main]]
name = "Categories"
url = "categories/"
weight = 4
[[menu.main]]
name = "Posts"
url = "posts/"
weight = 3
[[menu.main]]
name = "Projects"
url = "projects/"
weight = 2
[outputs]
home = ["HTML", "RSS", "JSON"]
[params]
author = "Paweł Weselak"
colorScheme = "auto"
commit = "https://github.com/frenchu/pragmatic-programming/tree"
dateformat = "January 2, 2006"
description = "Paweł Weselak pragmatyczne programowanie"
footerContent = "Everything should be as simple as possible, but not simplier."
gravatar = "frenchu@o2.pl"
hideCopyright = false
hideCredits = false
hideFooter = false
info = "Senior Software Developer"
keywords = "blog,developer,personal"
maxSeeAlsoItems = 5
rtl = false
since = 2010
[[params.social]]
icon = "fab fa-github"
name = "Github"
url = "https://github.com/frenchu/"
weight = 1
[[params.social]]
icon = "fab fa-gitlab"
name = "Gitlab"
url = "https://gitlab.com/frenchu/"
weight = 2
[[params.social]]
icon = "fab fa-stack-overflow"
name = "Stackoverflow"
url = "https://stackoverflow.com/users/4871030/pawe%c5%82-weselak"
weight = 3
[[params.social]]
icon = "fab fa-linkedin"
name = "LinkedIn"
url = "https://www.linkedin.com/in/pawel-weselak/"
weight = 4
[taxonomies]
category = "categories"
series = "series"
tag = "tags"
